In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [9]:
## define the vocabolart size
voc_size=10000

In [24]:
### one-hot Representaion
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[8368, 2413, 8404, 7812],
 [8368, 2413, 8404, 4420],
 [8368, 4849, 8404, 4145],
 [9407, 3898, 5087, 9373, 4497],
 [9407, 3898, 5087, 9373, 1688],
 [5344, 8368, 568, 8404, 4249],
 [7774, 612, 4614, 9373]]

In [25]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [13]:
import numpy as np

In [20]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8368 2413 8404 7812]
 [   0    0    0    0 8368 2413 8404 4420]
 [   0    0    0    0 8368 4849 8404 4145]
 [   0    0    0 9407 3898 5087 9373 4497]
 [   0    0    0 9407 3898 5087 9373 1688]
 [   0    0    0 5344 8368  568 8404 4249]
 [   0    0    0    0 7774  612 4614 9373]]


In [21]:
### feature representation
dim=10


In [22]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step


array([[[-3.8071085e-02,  1.2225367e-02, -9.3459859e-03, -4.7725368e-02,
          2.3409653e-02,  4.2005453e-02, -4.5888137e-02, -3.8478862e-02,
          1.0182776e-02,  1.6662966e-02],
        [-3.8071085e-02,  1.2225367e-02, -9.3459859e-03, -4.7725368e-02,
          2.3409653e-02,  4.2005453e-02, -4.5888137e-02, -3.8478862e-02,
          1.0182776e-02,  1.6662966e-02],
        [-3.8071085e-02,  1.2225367e-02, -9.3459859e-03, -4.7725368e-02,
          2.3409653e-02,  4.2005453e-02, -4.5888137e-02, -3.8478862e-02,
          1.0182776e-02,  1.6662966e-02],
        [-3.8071085e-02,  1.2225367e-02, -9.3459859e-03, -4.7725368e-02,
          2.3409653e-02,  4.2005453e-02, -4.5888137e-02, -3.8478862e-02,
          1.0182776e-02,  1.6662966e-02],
        [ 8.1540458e-03,  2.7880695e-02,  3.7159037e-02,  4.5552142e-03,
         -4.3281771e-02, -4.3365300e-02, -1.2472473e-02, -4.9089577e-02,
          1.0084115e-02, -4.2901672e-02],
        [ 1.0913372e-02, -3.1365432e-02, -4.0380120e-02, -2.

In [ ]:
embedded_docs[0]